Complete cycle
fintual-oss/paraffin-back pull request #30
Opened 2022-11-07 03:24 UTC by AlehandroL

# Base PR
- PR based on main branch

# Context
- With this PR, we are building the basic functionality to mark cycles as completed, and also show wether a cycle is completed or not in all the existing endpoints.

# Changelog
- Create routes and methods for completing a cycle
- Include 'completed' attribute in all cycle's endpoints

2022-11-07 13:21 UTC, iaheck requested changes
we should include tests on these new endpoints

2022-11-08 19:41 UTC, vpulgar approved these changes

2022-11-08 19:49 UTC, jjsantos01 approved these changes
I left some minor comments just for the record, you can mark as resolved and merge.

2022-11-08 19:58 UTC, AlehandroL commented on app/controllers/api/cycles_controller.rb
> +      state.completed_at ? true : false
Changed the way is written but kept the 2 lines, since I believe the one-liner is harder to understand

2022-11-08 20:07 UTC, AlehandroL commented on app/controllers/api/cycles_controller.rb
> +      code = 200
Done! thanks!

2022-11-08 20:25 UTC, jjsantos01 approved these changes

2022-11-08 20:25 UTC, merged